syntax = "proto3";

option csharp_namespace = "IdentityService.Grpc";

message Feedback {
  string id = 1;
  string question_answer_id = 2;
  string examiner_id = 3;
  string comment = 4;
  int32 rating = 5;
  // Optional related entities
  optional QuestionAnswer question_answer = 6;
}

// Entity definitions
message Question {
  string id = 1;  // GUID as string
  string quiz_id = 2;
  string question_type = 3;
  string question_text = 4;
  string options = 5;
  string correct_answer = 6;
  int32 max_score = 7;
  int32 order = 8;
  // Optional related entities
  optional Quiz quiz = 9;
  repeated string question_answers_ids = 10;
}

message QuestionAnswer {
  string id = 1;
  string question_id = 2;
  string quiz_response_id = 3;
  string answer_text = 4;
  string selected_options = 5;
  // Optional related entities
  optional Question question = 6;
  optional QuizResponse quiz_response = 7;
  repeated string feedbacks_ids = 8;
}

message Quiz {
  string id = 1;
  string course_item_id = 2;
  string title = 3;
  string type = 4;
  string description = 5;
  // Optional related entities
  repeated string questions_ids = 6;
  repeated string quiz_responses_ids = 7;
}

message QuizResponse {
  string id = 1;
  string quiz_id = 2;
  string identity_id = 3;
  // Optional related entities
  optional Quiz quiz = 4;
  repeated string question_answers_ids = 5;
}

message Profile {
  string id = 1;
  string identity_id = 2;
  string firstname = 3;
  string lastname = 4;
  string middlename = 5;
  string status = 6;
  string profile_image_url = 7;
}